import type { CollectionConfig } from 'payload'

export const Leads: CollectionConfig = {
  slug: 'leads',
  labels: { singular: 'Lead', plural: 'Leads' },
  admin: {
    useAsTitle: 'email',
    defaultColumns: ['email', 'source', 'organisme', 'nom', 'createdAt'],
    group: 'Marketing',
  },
  access: {
    read: ({ req: { user } }) => Boolean(user),
    create: () => true,
    update: ({ req: { user } }) => Boolean(user),
    delete: ({ req: { user } }) => user?.role === 'admin',
  },
  fields: [
    {
      name: 'source',
      type: 'select',
      required: true,
      options: [
        { label: 'Contact', value: 'contact' },
        { label: 'Démo', value: 'demo' },
      ],
      index: true,
    },
    { name: 'nom', type: 'text', required: true },
    { name: 'email', type: 'email', required: true, index: true },
    { name: 'organisme', type: 'text' },
    { name: 'message', type: 'textarea' },
    { name: 'titreReferentiel', type: 'text' },
    { name: 'tailleEtablissement', type: 'text' },
    { name: 'nbApprenants', type: 'number' },
    { name: 'dateLancementSouhaitee', type: 'date' },
    { name: 'dateHeureDemoSouhaitee', type: 'date' },
    { name: 'consentRgpd', type: 'checkbox' },
    {
      name: 'tracking',
      type: 'group',
      label: 'Tracking (last-touch)',
      admin: { description: 'Rempli automatiquement, non visible par le visiteur. Reflète la dernière source connue.' },
      fields: [
        { name: 'utmSource', type: 'text' },
        { name: 'utmMedium', type: 'text' },
        { name: 'utmCampaign', type: 'text', index: true },
        { name: 'utmTerm', type: 'text' },
        { name: 'utmContent', type: 'text' },
        { name: 'gclid', type: 'text' },
        { name: 'fbclid', type: 'text' },
        { name: 'referrer', type: 'text' },
        { name: 'sourcePage', type: 'text' },
        { name: 'userAgent', type: 'text' },
        { name: 'ip', type: 'text' },
      ],
    },
    {
      name: 'firstTouch',
      type: 'group',
      label: 'First-touch (acquisition initiale)',
      admin: { description: 'Capturé via cookie syl_first_touch (immutable 30j). Source d\'acquisition de référence pour l\'attribution B2B.' },
      fields: [
        { name: 'utmSource', type: 'text' },
        { name: 'utmMedium', type: 'text' },
        { name: 'utmCampaign', type: 'text' },
        { name: 'utmTerm', type: 'text' },
        { name: 'utmContent', type: 'text' },
        { name: 'gclid', type: 'text' },
        { name: 'fbclid', type: 'text' },
        { name: 'referrer', type: 'text' },
        { name: 'landing', type: 'text' },
        { name: 'at', type: 'date' },
      ],
    },
    {
      name: 'twentySync',
      type: 'group',
      label: 'Sync Twenty CRM',
      fields: [
        { name: 'twentyPersonId', type: 'text', admin: { readOnly: true } },
        { name: 'twentyCompanyId', type: 'text', admin: { readOnly: true } },
        { name: 'twentyOpportunityId', type: 'text', admin: { readOnly: true } },
        { name: 'twentySyncStatus', type: 'select', options: [
          { label: 'En attente', value: 'pending' },
          { label: 'Synchronisé', value: 'synced' },
          { label: 'Erreur', value: 'error' },
        ], defaultValue: 'pending' },
        { name: 'twentySyncError', type: 'textarea', admin: { readOnly: true } },
      ],
    },
    {
      name: 'calSync',
      type: 'group',
      label: 'Sync Cal.com',
      fields: [
        { name: 'calBookingUid', type: 'text', admin: { readOnly: true } },
        { name: 'calBookingId', type: 'number', admin: { readOnly: true } },
        { name: 'calBookingStatus', type: 'select', options: [
          { label: 'Non applicable', value: 'na' },
          { label: 'En attente', value: 'pending' },
          { label: 'Réservé', value: 'booked' },
          { label: 'Erreur', value: 'error' },
        ], defaultValue: 'na' },
        { name: 'calBookingError', type: 'textarea', admin: { readOnly: true } },
      ],
    },
  ],
}
